language: python

python:
    - "3.5"
    - "3.6"
    - "3.7-dev"

install:
    - pip install -U -e .[dev]
    - pip freeze

script:
    - coverage run --branch --source termtosvg -m unittest -v
    - coverage report

notifications:
  email: false
